/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Euler_2 {
  
  
  public static void main(String[] args) { 
    fib(100);
  }
  public static void fib(int a){ // Luodaan uusi metodi fib
    int x = 0; // alkuarvot
    int y = 1;
    int sum = 0;
    for(int i = 0; i < a && y < 4000000; i++){
    int edellinen = x; //edellinen luku on 0
    x = y; // x on nyt edellinen + y
    y = edellinen + y; // y = edellinen + y
    System.out.println(x); // Tulostetaan x
    if(x % 2 == 0){
    sum = sum+x;
    }
    }
    System.out.println(sum);
  /* ADD YOUR CODE HERE */
  }
}
